from adafruit_hid.keycode import Keycode

keys = {84: Keycode.ESCAPE,
        79: Keycode.ONE,
        74: Keycode.TWO,
        9: Keycode.THREE,
        14: Keycode.FOUR,
        19: Keycode.FIVE,
        24: Keycode.SIX,
        29: Keycode.SEVEN,
        34: Keycode.EIGHT,
        39: Keycode.NINE,
        44: Keycode.ZERO,
        49: Keycode.MINUS,
        4: Keycode.EQUALS,
        59: Keycode.BACKSPACE,
        64: Keycode.HOME,
        83: Keycode.TAB,
        78: Keycode.Q,
        73: Keycode.W,
        8: Keycode.E,
        13: Keycode.R,
        18: Keycode.T,
        23: Keycode.Y,
        28: Keycode.U,
        33: Keycode.I,
        38: Keycode.O,
        43: Keycode.P,
        48: Keycode.LEFT_BRACKET,
        3: Keycode.RIGHT_BRACKET,
        58: Keycode.BACKSLASH,
        63: Keycode.DELETE,
        82: Keycode.CAPS_LOCK,
        72: Keycode.A,
        7: Keycode.S,
        12: Keycode.D,
        17: Keycode.F,
        22: Keycode.G,
        27: Keycode.H,
        32: Keycode.J,
        37: Keycode.K,
        42: Keycode.L,
        47: Keycode.SEMICOLON,
        2: Keycode.QUOTE,
        57: Keycode.ENTER,
        69: Keycode.PAGE_UP,
        81: Keycode.LEFT_SHIFT,
        71: Keycode.Z,
        6: Keycode.X,
        11: Keycode.C,
        16: Keycode.V,
        21: Keycode.B,
        26: Keycode.N,
        31: Keycode.M,
        36: Keycode.COMMA,
        41: Keycode.PERIOD,
        46: Keycode.FORWARD_SLASH,
        56: Keycode.RIGHT_SHIFT,
        51: Keycode.UP_ARROW,
        68: Keycode.PAGE_DOWN,
        80: Keycode.LEFT_CONTROL,
        70: Keycode.LEFT_GUI,
        5: Keycode.LEFT_ALT,
        20: Keycode.SPACE,
        40: Keycode.RIGHT_ALT,
        55: Keycode.RIGHT_CONTROL,
        60: Keycode.LEFT_ARROW,
        50: Keycode.DOWN_ARROW,
        65: Keycode.RIGHT_ARROW,
        }


fn_keys = {84: Keycode.GRAVE_ACCENT,
           79: Keycode.F1,
           74: Keycode.F2,
           9: Keycode.F3,
           14: Keycode.F4,
           19: Keycode.F5,
           24: Keycode.F6,
           29: Keycode.F7,
           34: Keycode.F8,
           39: Keycode.F9,
           44: Keycode.F10,
           49: Keycode.F11,
           4: Keycode.F12,
           }